services:
  hzfirst:
    image: hazelcast/hazelcast:5.1.1
    networks:
      - hznet

  hz:
    image: hazelcast/hazelcast:5.1.1
    networks:
      - hznet

  mc:
    image: hazelcast/management-center:5.1 
    ports:
      - "8080:8080"
    networks:
      - hznet

  # cli:
  #   image: hazelcast/hazelcast:5.1.1
  #   command: hz-cli 
  #   networks:
  #     - hznet

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev 
    volumes:
      - ".:/project"
    networks:
      - hznet


networks:
  hznet: 
